Vagrant.configure("2") do |config|
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.define "nodo1" do |nodo1|
		nodo1.vm.box="debian/bullseye64"
		nodo1.vm.hostname="nodo1"
		nodo1.vm.network "private_network",
			:libvirt__network_name => "Redpriv",
			:libvirt__dhcp_enabled => false,
			:ip => "10.0.0.1",
			:libvirt__forward_mode => "none"
	end
	config.vm.define "nodo2" do |nodo2|
		nodo2.vm.box="generic/ubuntu2010"
		nodo2.vm.hostname="nodo2"
		nodo2.vm.provider :libvirt do |libvirt|
			libvirt.storage :file, :size => '1G'
			libvirt.storage :file, :size => '1G'
		end
		nodo2.vm.network "private_network",
			:libvirt__network_name => "Redpriv",
			:libvirt__dhcp_enabled => false,
			:ip => "10.0.0.2",
			:libvirt__forward_mode => "none"
		nodo2.vm.network "public_network",
			:dev => "br0",
			:mode => "bridge",
			:type => "bridge",
			use_dhcp_assigned_default_route: true
		nodo2.vm.provision "shell",
			run: "always",
			inline: "ip route del default via 192.168.121.1 || true"
	end
end
