Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.hostname="prueba-taller5"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "public_network", ip: "192.168.121.167"
    config.vm.provider :libvirt do |libvirt|
         libvirt.memory = 1024
         libvirt.cpus = 2
    end
    config.vm.provision "ansible" do |ansible|
	ansible.playbook = "ansible/site.yaml"
    end
end
